name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'day1/**' 
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 588738611111.dkr.ecr.eu-north-1.amazonaws.com
    - name: Build, Tag, and Push Docker Image
      run: |
        docker build -t 588738611111.dkr.ecr.ap-south-1.amazonaws.com/bootcampflask:day2 day1/
        docker push 588738611111.dkr.ecr.ap-south-1.amazonaws.com/bootcampflask:day2